import { execSync } from "child_process";
import {
  ensureGitRepo,
  resolveRef,
  getCommits,
  getCommitsInclusive,
  getFullCommitDiffs,
  estimateDiffTokens,
  type CommitInfo,
} from "../git.js";
import {
  CODE_REVIEW_SYSTEM_PROMPT,
  buildCodeReviewUserMessage,
} from "../prompt.js";
import { callLlm, getModelContextWindow, type LlmOptions } from "../llm.js";
import {
  buildReviewHeader,
  resolveOutputPath,
  writeOutputFile,
} from "../output.js";

// ---------------------------------------------------------------------------
// GitHub PR review
// ---------------------------------------------------------------------------

export interface GitHubPrReviewOptions extends LlmOptions {
  prRef: string;
  save?: boolean;
  output?: string;
}

/**
 * Returns a normalized gh-compatible PR ref (URL or number string) if the
 * input looks like a GitHub PR reference, otherwise null.
 * Accepts: full URLs, bare numbers ("550"), or hash-prefixed numbers ("#550").
 */
export function parseGitHubPrRef(
  ref: string
): string | null {
  if (/github\.com\/[^/]+\/[^/]+\/pull\/\d+/.test(ref)) return ref;
  if (/^#?\d+$/.test(ref)) return ref.replace(/^#/, "");
  return null;
}

function gh(args: string): string {
  try {
    return execSync(`gh ${args}`, {
      encoding: "utf-8",
      stdio: ["pipe", "pipe", "pipe"],
    }).trim();
  } catch (err: any) {
    const stderr = err.stderr?.toString().trim() || err.message;
    throw new Error(`gh ${args.split(" ")[0]} failed: ${stderr}`);
  }
}

export async function reviewGitHubPrCommand(
  options: GitHubPrReviewOptions
): Promise<void> {
  const prRef = options.prRef;

  if (options.verbose) {
    console.error(`Fetching PR ${prRef} via gh...`);
  }

  // Fetch PR metadata via gh (works for URLs and numbers alike)
  const metaJson = gh(
    `pr view ${prRef} --json number,title,body,author,baseRefName,headRefName,url`
  );
  const meta = JSON.parse(metaJson) as {
    number: number;
    title: string;
    body: string;
    author: { login: string };
    baseRefName: string;
    headRefName: string;
    url: string;
  };

  // Get owner/repo from the resolved PR URL (e.g. https://github.com/owner/repo/pull/N)
  const urlMatch = meta.url.match(/github\.com\/([^/]+)\/([^/]+)\/pull\//);
  const repoDisplay = urlMatch ? `${urlMatch[1]}/${urlMatch[2]}` : "";

  // Fetch diff via gh
  const diff = gh(`pr diff ${prRef}`);

  const today = new Date().toISOString().split("T")[0];
  const header = `# Code Review: PR #${meta.number} — ${meta.title}

> **Repo:** ${repoDisplay}
> **Author:** ${meta.author?.login ?? "unknown"}
> **PR URL:** ${meta.url}
> **Base → Head:** \`${meta.baseRefName}\` → \`${meta.headRefName}\`
> Generated by git-genie on ${today}

`;

  const userMessage = `Review the following GitHub Pull Request:

## PR #${meta.number}: ${meta.title}
**Author:** ${meta.author?.login ?? "unknown"}
**Description:**
${meta.body || "(no description)"}

## Diff:
\`\`\`diff
${diff}
\`\`\`

Provide a thorough code review.`;

  if (options.verbose) {
    const estimatedTokens = Math.ceil(
      (userMessage.length + header.length) / 4
    );
    console.error(`Estimated diff size: ~${Math.round(estimatedTokens / 1000)}k tokens`);
    console.error("");
  }

  process.stdout.write(header);

  const result = await callLlm(CODE_REVIEW_SYSTEM_PROMPT, userMessage, options);

  if (options.save || options.output) {
    const outputPath =
      options.output ?? `notes/review-${today}-pr${meta.number}.md`;
    writeOutputFile(outputPath, header + result.content);
  }
}

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface ReviewOptions extends LlmOptions {
  startRef: string;
  endRef?: string;
  save?: boolean;
  output?: string;
}

// ---------------------------------------------------------------------------
// Command
// ---------------------------------------------------------------------------

export async function reviewCommand(options: ReviewOptions): Promise<void> {
  ensureGitRepo();

  // Resolve refs
  const startRefInfo = resolveRef(options.startRef);
  const endRefInfo = options.endRef
    ? resolveRef(options.endRef)
    : null;

  // Get commits
  let commits: CommitInfo[];

  if (endRefInfo) {
    // Range: inclusive of both endpoints
    commits = getCommitsInclusive(options.startRef, options.endRef!);
  } else {
    // Single commit
    commits = [
      {
        hash: startRefInfo.hash,
        shortHash: startRefInfo.hash.substring(0, 6),
        author: "", // Will be filled from git show
        date: "",
        subject: "",
        body: "",
      },
    ];

    // Get the actual commit info
    try {
      const info = execSync(
        `git log -1 --format="%an%n%ad%n%s%n%b" "${startRefInfo.hash}"`,
        { encoding: "utf-8" }
      ).trim();
      const lines = info.split("\n");
      commits[0].author = lines[0] || "";
      commits[0].date = lines[1] || "";
      commits[0].subject = lines[2] || "";
      commits[0].body = lines.slice(3).join("\n").trim();
    } catch {
      // Continue with empty metadata — the diff is what matters
    }
  }

  if (commits.length === 0) {
    console.error("No commits found in the specified range.");
    process.exit(1);
  }

  if (options.verbose) {
    const rangeDesc = endRefInfo
      ? `${startRefInfo.displayName}..${endRefInfo.displayName}`
      : startRefInfo.displayName;
    console.error(`Reviewing ${commits.length} commit(s): ${rangeDesc}`);
    console.error("Collecting diffs...");
    console.error("");
  }

  // Check if total diff size fits in context window
  const estimatedTokens = estimateDiffTokens(commits);
  const contextWindow = getModelContextWindow(options.provider, options.model);
  // Reserve ~20% for system prompt + response
  const availableTokens = Math.floor(contextWindow * 0.8);

  if (estimatedTokens > availableTokens) {
    console.error(
      `Error: diff too large (estimated ~${Math.round(estimatedTokens / 1000)}k tokens, model limit ~${Math.round(availableTokens / 1000)}k available).`
    );
    console.error(
      "Try reviewing fewer commits. For example:"
    );
    if (endRefInfo) {
      console.error(
        `  gitgenie review ${startRefInfo.displayName} <a-closer-commit>`
      );
    } else {
      console.error(
        "  The single commit's diff exceeds the context window."
      );
    }
    process.exit(1);
  }

  if (options.verbose) {
    console.error(
      `Estimated diff size: ~${Math.round(estimatedTokens / 1000)}k tokens (${Math.round(availableTokens / 1000)}k available)`
    );
    console.error("");
  }

  // Get full diffs (no truncation for review)
  const commitDiffs = getFullCommitDiffs(commits);

  // Build header
  const header = buildReviewHeader(
    startRefInfo,
    endRefInfo,
    commits.length
  );

  // Determine output path
  const targetRef = endRefInfo || startRefInfo;
  const outputPath = resolveOutputPath(
    { save: options.save, output: options.output },
    "review",
    targetRef
  );

  // Print header
  process.stdout.write(header);

  // Build user message and call LLM
  const userMessage = buildCodeReviewUserMessage(commitDiffs);

  const result = await callLlm(
    CODE_REVIEW_SYSTEM_PROMPT,
    userMessage,
    options
  );

  // Save if requested
  if (outputPath) {
    const fullContent = header + result.content;
    writeOutputFile(outputPath, fullContent);
  }
}
