import { existsSync, mkdirSync, writeFileSync } from "fs";
import { dirname, resolve } from "path";
import type { RefInfo } from "./git.js";

// ---------------------------------------------------------------------------
// Markdown header generation
// ---------------------------------------------------------------------------

export function buildReleaseNotesHeader(
  fromRef: RefInfo,
  toRef: RefInfo,
  commitCount: number
): string {
  const today = new Date().toISOString().split("T")[0];

  return `# Release Notes: ${fromRef.displayName} → ${toRef.displayName}

> Generated from commits after \`${fromRef.displayName}\` up to and including \`${toRef.displayName}\` (${commitCount} commits)
> Generated by git-genie on ${today}

`;
}

export function buildReviewHeader(
  startRef: RefInfo,
  endRef: RefInfo | null,
  commitCount: number
): string {
  const today = new Date().toISOString().split("T")[0];

  if (!endRef) {
    // Single commit
    return `# Code Review: ${startRef.displayName}

> Reviewing commit \`${startRef.displayName}\` (${commitCount} commit)
> Generated by git-genie on ${today}

`;
  }

  return `# Code Review: ${startRef.displayName}..${endRef.displayName}

> Reviewing commits \`${startRef.displayName}\` through \`${endRef.displayName}\` (inclusive, ${commitCount} commits)
> Generated by git-genie on ${today}

`;
}

// ---------------------------------------------------------------------------
// File output
// ---------------------------------------------------------------------------

export type OutputType = "release" | "review";

/**
 * Build the auto-generated filename for --save.
 */
export function buildSaveFilename(
  type: OutputType,
  targetRef: RefInfo
): string {
  const today = new Date().toISOString().split("T")[0];
  return `notes/${type}-${today}-${targetRef.displayName}.md`;
}

/**
 * Write markdown content to a file. Creates parent directories as needed.
 */
export function writeOutputFile(filePath: string, content: string): void {
  const resolved = resolve(filePath);
  const dir = dirname(resolved);

  if (!existsSync(dir)) {
    mkdirSync(dir, { recursive: true });
  }

  writeFileSync(resolved, content, "utf-8");
  console.error(`\nSaved to: ${resolved}`);
}

/**
 * Determine the output file path based on flags.
 * --output takes precedence over --save.
 */
export function resolveOutputPath(
  flags: { save?: boolean; output?: string },
  type: OutputType,
  targetRef: RefInfo
): string | null {
  if (flags.output) {
    return flags.output;
  }
  if (flags.save) {
    return buildSaveFilename(type, targetRef);
  }
  return null;
}
